### ISSUE TITLE
The sample does not work any more.

### ISSUE THREAD

**Issue by bencevegert** [DevExpress-Examples/how-to-print-the-scheduler-using-scheduler-reporting-t581109#1]
The sample does not work any more.

**Comment by AndreyMarten** [comment]
Hello,

I tested this project with the latest version of our controls (v18.2.7 at the moment), and on my side everything operates as expected. Could you please create a ticket in our **Support Center** and provide more information about what does not work in this project on your side.  Use this link: [Ask Your Question](https://www.devexpress.com/Support/Center/Question/Create). We will be happy to assist you there. 

Thanks,
Andrey
